services:
  - type: web
    name: Hashtags Mech Django app
    env: python
    buildCommand: pip install -r project_hashtags/requirements.txt && python manage.py collectstatic --no-input
    startCommand: cd project_hashtags && gunicorn hashtags_mech.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_hashtags.settings.production
      - key: SECRET_KEY
        sync: false  # Set this in the Render dashboard
    autoDeploy: true

  - type: static
    name: Hashtag Mech react app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /home
        destination: /
